### ISSUE TITLE
./write-edid.sh: line 72: line: command not found

### ISSUE THREAD

**Issue by Thra11** [ChalkElec/write-edid#1]
./write-edid.sh: line 72: line: command not found

The code in question is:

```
getOneLine ()
{
   line=$(line) || [ \! -z "$line" ]
}
```

From my understanding of bash, $(line) should run a command named line. However, it can't find any such command as a bash builtin or in my $PATH. I am using "GNU bash, version 4.3.33(1)-release (armv7l-unknown-linux-gnueabihf)" (on archlinuxarm). What should the command called 'line' be?

**Comment by ChalkElec** [comment]
It reads bytes from EDID file line by line (see lines 75-79). For text EDID file we simply "cat" it (line 76), for binary EDID file we print it with "xxd" command, then function getOneLine() reads printed file line by line to parse for hex bytes. Most probably you invoke script without parameters or with wrong link to EDID file.

**Comment by Thra11** [comment]
I am invoking the script as root using:
    ./write-edid.sh 1 edid_auo14.bin

I enabled debug trace on the bash script to see exactly what it was doing. The output is as follows:

```
+ PROGRAM_STRING=write
+ BUS=
+ FILE=
++ getopt -o bh --longoptions binary,hexadecimal -n write -- 1 edid_auo14.bin
+ ARGS=' -- '\''1'\'' '\''edid_auo14.bin'\'''
+ eval set -- -- ''\''1'\''' ''\''edid_auo14.bin'\'''
++ set -- -- 1 edid_auo14.bin
+ binaryMode=1
+ true
+ case "$1" in
+ shift
+ break
+ '[' 2 -lt 1 -o 2 -gt 2 ']'
+ BUS=1
+ '[' 2 -lt 2 ']'
+ FILE=edid_auo14.bin
+ '[' '!' -f edid_auo14.bin ']'
+ '[' '!' -r edid_auo14.bin ']'
+ IFSBAK='  
'
+ export 'IFS= 
'
+ IFS=' 
'
+ edidLength=128
+ count=0
+ chipAddress=0x50
+ '[' 1 -eq 0 ']'
+ xxd -p -g 0 -u -c 1 -l 128 edid_auo14.bin
+ getOneLine
++ line
./write-edid.sh: line 73: line: command not found
+ line=
+ '[' '!' -z '' ']'
+ IFS='     
'
+ echo 'Writing done, here is the output of i2cdump -y 1 0x50:'
Writing done, here is the output of i2cdump -y 1 0x50:
+ i2cdump -y 1 0x50
No size specified (using byte-data access)
Error: Could not set address to 0x50: Device or resource busy
+ exit
```

You can see that when it calls getOneLine for the first time, it tries to evaluate the command called line, which doesn't exist, so it prints an error and assigns nothing to the variable called line. As a result, the body of 'while getOnLine' is not executed, and it skips straight to the i2cdump part of the script. Unless there's a different version of bash which behaves differently to the version I have, I can't see how it could possibly work, but presumably it works for you, otherwise you wouldn't have committed it...

**Comment by ChalkElec** [comment]
I guess the problem is with different bash versions. The simplest way for you could be changing line 78 from "fi | while getOneLine ; do" to "fi | while read line ; do".

**Comment by Zibri** [comment]
yep.. change it directly in the code... "fi | while read line ; do" works and is also cleaner.

**Comment by Zibri** [comment]
unfortunateli in my laptop, monitor edid is read-only.. writing to it does nothing.. I tried also manually.

**Comment by ChalkElec** [comment]
Do you run it as root? 
Also, your EDID EEPROM chip can have WP (write protect) pin tied to power, then all writes operations will be blocked by chip.

**Comment by hereisderek** [comment]
I wasn't able to write presumably due the the write protection reason.
can't figure out how to byepass it yet

**Comment by ChalkElec** [comment]
sudo?
